[EPICSYSTEM-11] add project search and results table components
bcgov/epic-public pull request #3
Opened 2024-03-19 21:01 UTC by Ckoelewyn

2024-03-20 03:06 UTC, rpyyj commented
Please resolve the conflicts

2024-03-25 04:40 UTC, rpyyj commented
Whoa! It's great to see actual search results! Apologies for taking so long with the review but there is a lot to unpack.

2024-03-28 04:00 UTC, rpyyj requested changes

2024-03-28 04:00 UTC, rpyyj commented on src/components/Filter.js
> +import { PROJECT_LEGISLATION_YEARS } from "constants";
Please remove these unused constant imports. (These show up as `eslint` warnings in your `npm start` console.)

2024-03-28 04:00 UTC, rpyyj commented on src/components/Filter.js
> +const Filter = ({ filterKey, icon, items = [], onChange, selected, title }) => {
Please remove the `filterKey` prop

2024-03-28 04:00 UTC, rpyyj commented on src/components/Filter.js
> +	filterKey: PropTypes.string,
Please remove the `filterKey` prop type

2024-03-28 04:00 UTC, rpyyj commented on src/components/Filter.js
> -
Please restore this line break between the state definitions and the hook call

2024-03-28 04:00 UTC, rpyyj commented on src/components/Filter.js
> +		overflowY: "auto",
Thank you for stopping the never-ending menu madness! Please move these two lines above `width` to keep the 🔤

2024-03-28 04:00 UTC, rpyyj commented on src/components/Results/ResultsPagination/PagePreviousButton/index.js
> +			<IconButton aria-label={label} disabled={isDisabled} onClick={handleOnClick} type="button">
Reminder to use `<Button>` here

2024-04-09 17:46 UTC, Ckoelewyn commented on src/components/Filter.js
> +import { PROJECT_LEGISLATION_YEARS } from "constants";
Updated in [b425df8](https://github.com/bcgov/epic-public/pull/3/commits/b425df8adcb5800bca27d62866f23b734f4aa0cc)

2024-04-09 17:47 UTC, Ckoelewyn commented on src/components/Filter.js
> +const Filter = ({ filterKey, icon, items = [], onChange, selected, title }) => {
updated in [b425df8](https://github.com/bcgov/epic-public/pull/3/commits/b425df8adcb5800bca27d62866f23b734f4aa0cc)

2024-04-09 17:47 UTC, Ckoelewyn commented on src/components/Filter.js
> -
updated in [b425df8](https://github.com/bcgov/epic-public/pull/3/commits/b425df8adcb5800bca27d62866f23b734f4aa0cc)

2024-04-09 17:47 UTC, Ckoelewyn commented on src/components/Results/ResultsPagination/PagePreviousButton/index.js
> +			<IconButton aria-label={label} disabled={isDisabled} onClick={handleOnClick} type="button">
updated in [b425df8](https://github.com/bcgov/epic-public/pull/3/commits/b425df8adcb5800bca27d62866f23b734f4aa0cc)

2024-04-09 17:47 UTC, Ckoelewyn commented on src/components/Filter.js
> +		overflowY: "auto",
updated in [b425df8](https://github.com/bcgov/epic-public/pull/3/commits/b425df8adcb5800bca27d62866f23b734f4aa0cc)

2024-04-09 17:47 UTC, Ckoelewyn commented on src/components/Filter.js
> +	filterKey: PropTypes.string,
updated in [b425df8](https://github.com/bcgov/epic-public/pull/3/commits/b425df8adcb5800bca27d62866f23b734f4aa0cc)

2024-04-16 15:24 UTC, marklise approved these changes

2024-04-16 15:24 UTC, merged