EPICSYSTEM-23 Add Pcp feed tests and combine header and footer
bcgov/epic-public pull request #4
Opened 2024-04-03 16:03 UTC by tolkamps1

2024-04-05 04:10 UTC, rpyyj requested changes
Tests! YAAASSS!

2024-04-05 04:10 UTC, rpyyj commented on src/components/PcpFeed/PcpCard.test.js
> +import "@testing-library/jest-dom";
We don't need to include this because it's in our `src/setupTests.js` file, which is loaded before every test file runs.

2024-04-05 04:10 UTC, rpyyj commented on src/components/PcpFeed/PcpCard.js
> +			if (isAfterDate(new Date(), dateCompleted)) {
Thank you!

2024-04-05 04:10 UTC, rpyyj commented on src/components/PcpFeed/index.test.js
> +import "@testing-library/jest-dom";
Same thing :)

2024-04-05 04:10 UTC, rpyyj commented on src/components/PcpFeed/index.test.js
> +		footerButton.click();
Rather than invoking the click function directly here, please import and use `fireEvent` from the react testing library.

`fireEvent.click(footerButton);`

2024-04-05 04:10 UTC, rpyyj commented on src/components/PcpFeed/index.test.js
> +		const footerButton = screen.getByRole("button", { name: "Search all Public Comment Periods >" });
Please add:

`expect(footerButton).toBeInTheDocument();`

I know the test will throw an error message if the `getByRole` fails to find the button; it's just a readability thing, explicitly conveying an assertion here.

2024-04-05 16:07 UTC, tolkamps1 commented on src/components/PcpFeed/PcpCard.test.js
> +import "@testing-library/jest-dom";
Removed in 1ae48d5

2024-04-05 16:08 UTC, tolkamps1 commented on src/components/PcpFeed/index.test.js
> +import "@testing-library/jest-dom";
Removed in 1ae48d5

2024-04-05 16:08 UTC, tolkamps1 commented on src/components/PcpFeed/index.test.js
> +		footerButton.click();
Updated in 1ae48d5

2024-04-05 16:08 UTC, tolkamps1 commented on src/components/PcpFeed/index.test.js
> +		const footerButton = screen.getByRole("button", { name: "Search all Public Comment Periods >" });
Updated in 1ae48d5

2024-04-08 04:50 UTC, rpyyj approved these changes

2024-04-08 04:51 UTC, merged